=== C4rl0s1103/Grados/Grado Superior/primero/LM/_xml/tema 1/personas.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,apellido1,apellido2)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>

=== C4rl0s1103/Grados/Grado Superior/primero/LM/_xml/tema 1/DTD externo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
    <persona>
        <nombre>Rosa</nombre>
        <apellido1>Casas</apellido1>
        <apellido2>Rueda</apellido2>
    </persona>
    <persona>
        <nombre>Sergio</nombre>
        <apellido1>Fuentes</apellido1>
        <apellido2>RÃ­o</apellido2>
    </persona>
</personas>
