=== C4rl0s1103/Grados/Grado Superior/primero/LM/_xml/tema 2/personas.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="personas">
   <xsd:complexType>
         <xsd:sequence>
         <xsd:element name="persona" maxOccurs="unbounded">
         <xsd:complexType>

         <xsd:sequence>
         <xsd:element name="nombre" type="xsd:string" maxOccurs="unbounded"/>
         <xsd:element name="apellido1" type="xsd:string"/>
         <xsd:element name="apellido2" type="xsd:string" minOccurs="0"/>
         <xsd:element name="telefono" type="xsd:string" minOccurs="0" maxOccurs="2"/>
         <xsd:element name="edad" type="xsd:string"/>
         <xsd:element name="lugar_nacimiento" type="xsd:string"/>
         <xsd:element name="codigo_postal" type="xsd:string"/>

         <xsd:element name="edad">
          <xsd:simpleType>
            <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="0"/>
            <xsd:maxInclusive value="110"/>
            </xsd:restriction>
          </xsd:simpleType>
         </xsd:element>
        <xsd:element name="lugar_nacimiento">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
               <xsd:minLength value="4"/>
               <xsd:maxLength value="45"/>
            </xsd:restriction>
        </xsd:simpleType>
        </xsd:element>
        <xsd:element name="codigo_postal">
         <xsd:simpleType>
            <xsd:restriction base="xsd:integer">
               <xsd:pattern value="[0-9]{5}"/>
            </xsd:restriction>
         </xsd:simpleType>
        </xsd:element>
        </xsd:sequence>
         <xsd:attribute  name="nacionalidad" type="xsd:string"  use="optional"/>
         <xsd:attribute name="id_persona" type="xsd:string" use="required"/>
        </xsd:complexType>
        </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>
</xsd:schema>

=== C4rl0s1103/Grados/Grado Superior/primero/LM/_xml/tema 2/XSD_esquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"   xsi:noNamespaceSchemaLocation="personas.xsd" >
    <persona nacionalidad="española" id_persona="A1111">
        <nombre>Rosa</nombre>
        <nombre>Clara</nombre>
        <apellido1>Casas</apellido1>
        <apellido2>Rueda</apellido2>
        <edad>23</edad>
        <lugar_nacimiento>Torrejón de Ardoz</lugar_nacimiento>
        <codigo_postal>28850</codigo_postal>
    </persona>
    <persona id_persona="B2222">
        <nombre>Sergio</nombre>
        <apellido1>Fuentes</apellido1>
        <apellido2>Rio</apellido2>
        <telefono>911111111</telefono>
    </persona>
    <persona nacionalidad="francesa" id_persona="C3333">
        <nombre>Lorena</nombre>
        <apellido1>Madrid</apellido1>
        <telefono>912222222</telefono>
        <telefono>601222222</telefono>
        <edad>27</edad>
    </persona>
    <persona id_persona="D4444">
        <nombre>Carlos</nombre>
        <apellido1>Flores</apellido1>
    </persona>
</personas>
